version: '3.8'
services:
  user_management:
    build:
      context: ./service_users
      dockerfile: Dockerfile
    container_name: user_management
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgresql+psycopg2://user:password@db:5432/user_management_db
      - SECRET_KEY=your-secret-key
      - ACCESS_TOKEN_EXPIRE_MINUTES=30
    volumes:
      - ./service_users:/app:ro
    depends_on:
      - db

  db:
    image: postgres:14
    container_name: db
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: user_management_db
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data:
